SWU_Web/Controllers/SystemMonitoringController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SWU_Web.Data;
using SWU_Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWU_Web.Controllers
{
    [Authorize]
    public class SystemMonitoringController : Controller
    {
        private readonly ILogger<SystemMonitoringController> _logger;
        private ApplicationDbContext _context;

        public SystemMonitoringController(ILogger<SystemMonitoringController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            MainPageModel model = new MainPageModel();
            Dictionary<int, float> lastValues = new Dictionary<int, float>();
            List<SWU_Web.Data.SwuSystem> systems = _context.Systems.Include(s => s.Detectors).ThenInclude(d => d.TypeDetector).ToList();

            foreach (List<Detector> detectors in systems.Select(s => s.Detectors.ToList()))
            {
                foreach (Detector detector in detectors)
                {
                    LogDetector log = _context.LogDetectors.OrderByDescending(l => l.Id).FirstOrDefault(l => l.DetectorId == detector.Id);

                    float lastValue = 0;
                    
                    if (log != null)
                    {
                        lastValue = log.Value;
                    }

                    lastValues.Add(detector.Id, lastValue);
                }
            }

            model.Systems = systems;
            model.LastDetectorsValue = lastValues;

            return View(model);
        }
        [HttpGet]
        public IActionResult ControlPanel()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Error()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetSystems()
        {
            List<SWU_Web.Data.SwuSystem> systems = _context.Systems.Include(s => s.Detectors).ThenInclude(d => d.TypeDetector).ToList();
            return Json(systems);
        }
    }
}

SWU_Web/Views/Shared/_Layout.cshtml
@using SWU_Web.Enums;
@inject SignInManager<User> SignInManager
@inject UserManager<User> userManager
@{
    User user = await userManager.GetUserAsync(User);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SWU_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="~/lib/datatables.net/css/jquery.dataTables.css" rel="stylesheet" />
    <script src="~/lib/datatables.net/jquery.dataTables.min.js"></script>
    <link href="~/lib/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
</head>
<body class="h-100">
    <header>
        @if (SignInManager.IsSignedIn(User))
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="SystemMonitoring" asp-action="Index">SWU</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @if (user != null)
                            {
                                @if (await userManager.IsInRoleAsync(user, Roles.SuperAdmin.ToString()))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AdminPanel">Users</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="SystemMonitoring" asp-action="ControlPanel">Systems</a>
                                    </li>
                                }
                            }

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SystemMonitoring" asp-action="Index">Home</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        }

    </header>
    <div class="container h-100">
        <main role="main" class="h-100 pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>